# Generated by Django 5.0.1 on 2024-01-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='News',
        ),
    ]
