# Generated by Django 5.0.1 on 2024-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_model_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default=" Juda zo'r yangilik", max_length=255),
            preserve_default=False,
        ),
    ]
